-- The SSCCAC bylaws in force (as amended April 9, 2022), transcribed from
-- ssccac_bylaws__amended_april_09_2022.pdf, plus the starter notes on
-- substantive differences from the draft. Idempotent.
delete from sscc_bylaws_adopted;
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-I-1$q$, 1, $q$I$q$, $q$Provision$q$, $q$Art. I §1$q$, $q$Purpose$q$, $q$The purpose of the South Shore Cultural Center Advisory Council herein called Council:

promote community interest and participation in developing cultural activities, art, music, recreational, social, and educational programs at the South Shore Cultural Center

Provide a forum to discuss South Shore Cultural Center concerns and interest in the arts.

Advise and make recommendations and work with the Chicago Park District (CPkD) on all operations of the Center.

Assist in funding and direct preservation for maintenance and beautification of the Center.

Promote the growth and development of the Center as a community regional and city- wide cultural facility.

Encourage long range planning of the Center.$q$, array[$q$I-1$q$, $q$I-2$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-1a$q$, 2, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §1$q$, $q$Membership$q$, $q$Council consists of three class of members, Individual, Family and Organizational. Membership requires submission of a membership form and payment of dues within a fiscal year. An Organization and Family are required to designate in writing one representative and one alternate who is entitled to represent the Family or Organization. Membership renewal form is required each year.$q$, array[$q$II-1$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-1b$q$, 3, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §1$q$, $q$Membership: CPD employees, applications, screening$q$, $q$Chicago Park District employees may be members; however, they may not hold office, and can only be non-voting members at the park where they are employed and are required to disclose their CPkD employment. Every member must complete a membership application. Any member whose work involve contact with children, or any finances must submit a volunteer application to the Chicago Park District and may be asked to submit to a criminal background check.$q$, array[$q$II-2$q$, $q$II-4$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-1c$q$, 4, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §1$q$, $q$Membership: open membership and nondiscrimination$q$, $q$There are no geographic limits to membership and no discrimination because of race, color, religion, sex, national origin, ancestry, marital status, physical handicap, unfavorable discharge from military service, or sexual orientation.$q$, array[$q$II-5$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-2$q$, 5, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §2$q$, $q$Membership Annual Dues$q$, $q$The Annual dues of membership is set by the Board of Directors and ratified by members entitled to vote. Annual membership dues for a fiscal year are based on January 1 and ending December 31st at the end of the year and required to be paid within the fiscal year. Annual Dues is $25 for Individual and $35 for Family and Organization per fiscal year. However, no person interested in becoming a member is excluded from membership for inability to pay such dues.$q$, array[$q$II-6$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-3$q$, 6, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §3$q$, $q$Member Removal$q$, $q$Any member or officer membership may be revoked for improper conduct deemed detrimental to COUNCIL upon a written motion to the officers containing the reason for removal and approval by a quorum vote of the voting membership.$q$, array[$q$II-8$q$, $q$V-10$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-3E$q$, 7, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §3(E)$q$, $q$Complaint Review Process (per Section E of the CPD Guidelines)$q$, $q$This review process is designed solely for the purpose of reviewing complaints from PACs regarding actions of members acting on behalf of their PAC.

1. The officers of the PAC have the responsibility of monitoring the actions and activities of their PAC. The objectives set by the individual PACs must be lawful, good for the community and not conflict with CPD policies.

2. The PAC has the right to review the actions of an individual member, officer, or group of members or officers acting on behalf of the PAC. The PAC may consider separation of a member, officer, or group of members or officers should they deem it appropriate based on just cause.

3. PACs should respond to any complaints in writing and file a copy of the response in the file kept at its respective park. Should the complainant be dissatisfied with the response, they have the right to appear before the PAC's general membership to voice their concern.

4. If the above procedures fail to reach an amicable conclusion the complainant has a right to file a written appeal with the PAC Oversight Committee, which details the complaint, the steps taken and the result. The Oversight Committee will provide the final opinion on the matter. For more information on the PAC Oversight Committee or how to become a member please contact the Department of Legislative and Community Affairs.$q$, array[$q$II-9$q$, $q$II-8$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-4$q$, 8, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §4$q$, $q$Regular and Annual Meeting$q$, $q$All meetings are open to the Public but only members in good standing are eligible to vote. Regular membership meetings shall be held on the second Saturday of each month. The Annual membership meeting for election shall be held the second Saturday in January or as soon thereafter as circumstances permit.$q$, array[$q$III-1$q$, $q$III-2$q$, $q$III-3$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-5$q$, 9, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §5$q$, $q$Meeting Notices$q$, $q$All notices of the membership meetings shall be posted at the South Shore Cultural Center 14 days prior to the meeting. Member notices will be sent via COUNCIL member email addresses and Calling Post if contact information has been provided.$q$, array[$q$III-4$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-II-6$q$, 10, $q$II$q$, $q$Membership and Meetings$q$, $q$Art. II §6$q$, $q$Emergency Governance Provision$q$, $q$The South Shore Cultural Center Advisory Council By-laws set forth here the procedures for holding regularly scheduled meetings in case of a major national or local state of emergency resulting in a disruption in normal life over multiple days or an extended period. The Chicago Park District recognizes that because of such emergencies, in-person meetings held at the South Shore Cultural Center may not be allowed. The Chicago Park District has asked that Councils amend their by-laws to allow virtual meetings in accordance with the Park District's guidance.

Virtual meetings, with a phone-in option, may be held in lieu of in-person meetings. The virtual meetings will begin at 10:30 a.m., unless a special time is set. All meetings will start with a virtual and written roll call. The agenda of the meeting and the minutes of the prior meeting will be made available 3 days before the virtual meeting will take place. Any notice of a virtual meeting will include instructions on how to join the meeting. All necessary emergency actions taken by the Board of Directors pursuant to this Article shall be deemed duly authorized and approved during which time the period of Major Emergency conditions exist.$q$, array[$q$III-6$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-III-1$q$, 11, $q$III$q$, $q$Voting$q$, $q$Art. III §1$q$, $q$General$q$, $q$Any vote at a membership meeting is valid with a quorum of 10 members that are eligible to vote. To amend the bylaws, voting requires 2/3 majority of eligible voting members.$q$, array[$q$IV-2$q$, $q$IV-5$q$, $q$IV-6$q$, $q$X-1$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-III-2$q$, 12, $q$III$q$, $q$Voting$q$, $q$Art. III §2$q$, $q$Members Eligible to Vote$q$, $q$Voting rights are extended to those members in good standing and only one vote per membership. There shall be NO voting by proxy. Members in good standing, have attended four meetings within a 12-month period (one in each quarter) and participated on a committee each fiscal year.

Voting rights are extended to those members in good standing and only one vote per membership. There shall be NO voting by proxy. Members in good standing, have attended four meetings within a 12-month period within a fiscal year.$q$, array[$q$IV-3$q$, $q$II-7$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-III-3$q$, 13, $q$III$q$, $q$Voting$q$, $q$Art. III §3$q$, $q$Nomination and Election$q$, $q$A Nominating Committee will be selected at the November membership meeting that consist of five not less than three eligible voting members. Nominations slated for the Board will be presented at the Annual Membership Meeting. Four officers will be elected for a one-year term or until a new officer can be elected. All nominees for officers shall be members good standing and reside in Chicago City limits per Chicago Park District guidelines.$q$, array[$q$VI-1$q$, $q$VI-2$q$, $q$VI-3$q$, $q$V-2$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-IV-1$q$, 14, $q$IV$q$, $q$Officers$q$, $q$Art. IV §1$q$, $q$Officers$q$, $q$The Elected Officers of the PAC shall consist of Four (4) members, President, Vice President, Secretary and Treasurer. All candidates for office shall have met membership and dues requirements and have been a member for one year. Officers are classified as Executive Board, and responsible for policymaking and implementation of Council decisions; and shall manage the COUNCIL affairs.$q$, array[$q$V-1$q$, $q$V-2$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-IV-2$q$, 15, $q$IV$q$, $q$Officers$q$, $q$Art. IV §2$q$, $q$Officers Duties$q$, $q$President shall officiate and prepare agenda for Membership and Board Meetings and is ex- officio of all Standing Committees.

Vice President shall officiate in the absence of the President and is ex-officio of all Standing Committees.

The Secretary takes minutes of official meetings, tracks attendance, and maintains records of which members are in good standing. Also keeps other records of the COUNCIL, provides notices of meetings and updates membership roster as provided by the Membership Committee.

The Treasurer shall have charge and custody of and be responsible for all funds of the COUNCIL; receive receipts, pay bills, and give monies due and payable to the COUNCIL from any source whatsoever, and deposit all such funds in the name of the COUNCIL into the Council's bank account. The Treasurer shall give financial statements at each meeting, and an itemized report once a year.$q$, array[$q$V-4$q$, $q$V-5$q$, $q$V-6$q$, $q$V-7$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-IV-3$q$, 16, $q$IV$q$, $q$Officers$q$, $q$Art. IV §3$q$, $q$Executive Board Meetings$q$, $q$The Executive Board consist of President, Vice President, Secretary and Treasurer and shall meet at least four times within a fiscal year. Three members of the Board Shall constitute a quorum.$q$, array[$q$V-8$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-V-1$q$, 17, $q$V$q$, $q$Committees and Appointed Position$q$, $q$Art. V §1$q$, $q$Standing Committees$q$, $q$Committees shall be composed of Council members and other volunteers. Committee Chairs shall be appointed by the Executive Board. The President and Vice President shall be ex-officio members of all committees and task forces, except for the nominating committee. Officers cannot serve as committee Chairs. Chairpersons shall insure that all general membership is given notice of committee meetings and provide reports at monthly membership meetings as well as a written report to the Secretary for record keeping. Committee chairs shall serve a one-year term. The Committees must meet at least quarterly during a fiscal year.

Performing Arts Committee develops and promotes art and music programs and events for the community.

Building and Grounds Committee shall review conditions of park facilities, equipment, and surrounding parkland, recommending repair, landscaping, renovation, or replacement where appropriate.

Program Committee shall determine the degree to which program offerings match resident needs, make programming recommendations to CPkD, develop, and organize specific cultural programs and events to engage our community approved by the Council.

Fundraising Committee shall solicit funds, sponsorships, grants, and other funding to assist the with development of cultural programming and fulfillment of community requests for program offerings.

Membership Committee shall work with all committees to recruit new members. Recruitment methods include staffing a membership table at Park events. The membership chair shall keep an up-to date roll of members, providing information to the secretary who records/maintains attendance roster.

Technical Committee – Tech committee shall be responsible for creating and maintaining the Council's social media profiles and content and assist with virtual meetings.$q$, array[$q$VII-1$q$, $q$VII-3$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-V-2$q$, 18, $q$V$q$, $q$Committees and Appointed Position$q$, $q$Art. V §2$q$, $q$Appointed Position$q$, $q$The Sergeant-at-arms: The Sergeant at Arms, under the appointment/direction of the presiding officers, maintains order and decorum among the members and all persons present at meetings.$q$, array[$q$VII-4$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-VI$q$, 19, $q$VI$q$, $q$By-Law Amendments$q$, $q$Art. VI$q$, $q$By-Law Amendments$q$, $q$The COUNCIL By-Laws can be amended through initiation of a motion, and submitted in writing, to the Secretary and is subject to a vote. A copy of all amendments shall be provided to the Chicago Park District.$q$, array[$q$IV-6$q$, $q$X-1$q$, $q$X-2$q$]::text[]);
insert into sscc_bylaws_adopted (key, sort, article_num, article_title, label, title, body, maps_to) values ($q$A-REC$q$, 20, $q$$q$, $q$Adoption record$q$, $q$Adoption record$q$, $q$Motions adopting and amending these bylaws$q$, $q$Motion: Barbara Wright Pryor moved bylaws be accepted as amended, second by Gary Ossewaarde and approved by the voting members present. March 13, 2021, membership meeting.

Motion – John Lloyd - to amend Article III Section Two – Members Eligible to Vote. Motion seconded. Yea, eight votes, and Nay three votes. Motion passed April 9, 2022$q$, '{}'::text[]);
do $d$ begin
if not exists (select 1 from sscc_bylaws_proposals where author_label = 'Comparison with 2022 bylaws') then
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$IV-2$q$, $q$IV$q$, $q$Quorum drops from 10 to 8$q$, $q$2022 Art. III §1: "Any vote at a membership meeting is valid with a quorum of 10 members that are eligible to vote." Draft IV.2 sets quorum at eight (8). Decide whether lowering the quorum is intended, and say so in the notice to members.$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$X-1$q$, $q$X$q$, $q$Amendment threshold changes: two-thirds of eligible voters (2022) vs. two-thirds of votes cast (draft)$q$, $q$2022 Art. III §1: "To amend the bylaws, voting requires 2/3 majority of eligible voting members." Draft X.1 and IV.6 require "a two-thirds vote of the votes cast, with a quorum present," which is a lower bar. Note that this revision itself must be adopted under the 2022 rule, since those are the bylaws in force. CPD's template uses "a favorable 2/3 vote of the general PAC members."$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$III-4$q$, $q$III$q$, $q$The 14-day posted notice for membership meetings is dropped$q$, $q$2022 Art. II §5: notices "shall be posted at the South Shore Cultural Center 14 days prior to the meeting." Draft III.4 requires posting but sets no advance period; the only time in the draft is "when feasible, at least forty-eight hours" for changes to a meeting (III.1).$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$III-2$q$, $q$III$q$, $q$Election meeting moves from January to November$q$, $q$2022 Art. II §4 holds the annual election meeting on "the second Saturday in January or as soon thereafter as circumstances permit." Draft III.2 moves it to the second Saturday in November, with new officers shadowing through December and taking office in January. The Nominating Committee moves from the November meeting (2022 Art. III §3) to September (draft VI.1).$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$V-2$q$, $q$V$q$, $q$Officer term of one year is no longer stated$q$, $q$2022 Art. III §3: "Four officers will be elected for a one-year term or until a new officer can be elected." The draft never states the length of an officer's term (V.9 and V.10 refer to "the term" without defining it). Consider restoring a term length, and whether there are term limits.$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$V-2$q$, $q$V$q$, $q$Chicago residency for officers is no longer stated$q$, $q$2022 Art. III §3: nominees for office shall "reside in Chicago City limits per Chicago Park District guidelines." Draft V.2 only refers to "any residency or other eligibility requirement" under CPD rules. CPD's Feb 2025 PAC Guidelines say "Only Chicago residents shall serve as officers" and that non-residents "may participate only as general members." Stating it plainly would avoid confusion.$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$II-2$q$, $q$II$q$, $q$CPD employee rules are now by reference rather than stated$q$, $q$2022 Art. II §1: CPD employees "may not hold office, and can only be non-voting members at the park where they are employed." Draft II.2 defers to "current Chicago Park District policies." The CPD Guidelines still state the same rule as 2022; consider keeping it explicit so members don't have to look it up.$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$II-5$q$, $q$II$q$, $q$Explicit protected classes and "no geographic limits" are removed$q$, $q$2022 Art. II §1: "There are no geographic limits to membership and no discrimination because of race, color, religion, sex, national origin, ancestry, marital status, physical handicap, unfavorable discharge from military service, or sexual orientation." Draft II.5 says only "without unlawful discrimination." CPD's template lists protected classes (and adds age, parental status, and mental disability). Decide whether to keep the explicit list and the open-membership statement.$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$II-8$q$, $q$II$q$, $q$Removal now needs a two-thirds vote with notice and a hearing$q$, $q$2022 Art. II §3: membership "may be revoked for improper conduct deemed detrimental to COUNCIL upon a written motion to the officers ... and approval by a quorum vote of the voting membership." Draft II.8 adds written notice, a chance to respond, fact-finding, and a two-thirds vote of votes cast. This is a substantial change the membership should see explained.$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$IV-3$q$, $q$IV$q$, $q$Voting eligibility: the 2022 text contains two conflicting versions$q$, $q$2022 Art. III §2 contains two paragraphs: one requires four meetings in 12 months "(one in each quarter)" and committee participation each fiscal year; the second, apparently the April 9, 2022 amendment, requires four meetings "within a 12-month period within a fiscal year" with no committee requirement. Draft IV.3 follows the second (four meetings in the preceding twelve months). Confirm from the April 2022 minutes which text was adopted, and note that the draft also drops "one in each quarter."$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$VII-1$q$, $q$VII$q$, $q$Committee rules loosened: meeting frequency, chair terms, officers as chairs$q$, $q$2022 Art. V §1: committees "must meet at least quarterly," chairs "serve a one-year term," and "Officers cannot serve as committee Chairs." Draft VII.1 requires meetings "at least every two months" (more often), drops the one-year chair term, and lets the Council authorize officers to chair committees. Membership and Technical committees are renamed (Membership and Community Outreach; Marketing and Technical).$q$, 'Comparison with 2022 bylaws');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$III-6$q$, $q$III$q$, $q$Virtual-meeting specifics from 2022 are dropped$q$, $q$2022 Art. II §6: virtual meetings "will begin at 10:30 a.m., unless a special time is set," start "with a virtual and written roll call," and the agenda and prior minutes are "made available 3 days before." Draft III.6 keeps electronic meetings but drops these specifics. Keep them, or leave them to meeting procedure?$q$, 'Comparison with 2022 bylaws');
end if;
end $d$;
update sscc_bylaws_proposals set rationale = $q$II.9 says appeals may go to "the CPD PAC Oversight Committee." That wording comes from the 2022 bylaws (Art. II §3(E)), which quoted an older edition of the CPD Guidelines. The current CPD PAC Guidelines (February 2025, Section G) route a written appeal to the Park Supervisor or Area Manager, who shares it with the Department of Legislative and Community Affairs and then the PAC Governance Committee, which follows the procedures in the PAC Code of Conduct. Update II.9 to name the current body and process, or refer to the Guidelines generally.$q$ where kind = 'issue' and section_key = 'II-9' and author_label = 'Starter review';
update sscc_bylaws_proposals set rationale = $q$V.8 requires Executive Board meetings "at least four times during each fiscal year." The draft defines only the membership year (II.6, January 1 to December 31). The 2022 bylaws tied dues to a fiscal year "based on January 1 and ending December 31st" (Art. II §2); the draft dropped that definition. Define the fiscal year, or use "membership year" throughout.$q$ where kind = 'issue' and section_key = 'V-8' and author_label = 'Starter review';
