-- Seed for the SSCC bylaws workspace: v1.0 = the clean revision draft
-- (one member's proposed rewrite of the 2022 bylaws, South_Shore_Cultural_Center_Advisory_Council_Clean_Bylaws_Revision.docx).
-- Run once, after sscc-bylaws-schema.sql. Idempotent: skips if v1.0 exists.
-- The subcommittee roster (sscc_bylaws_members) is added directly against
-- the live project, never committed: this repo is public and the roster
-- is members' personal email addresses (same rule as bios102_students).
do $seed$
begin
if exists (select 1 from sscc_bylaws_versions where num = 1) then return; end if;
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$I-1$q$, 1, $q$I$q$, $q$Name and Purpose$q$, 1, 1, $q$Name$q$, $q$The organization shall be known as the South Shore Cultural Center Advisory Council, hereinafter referred to as the “Council.”$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$I-2$q$, 1, $q$I$q$, $q$Name and Purpose$q$, 2, 2, $q$Purpose$q$, $q$The Council shall:

Promote community interest, participation, and engagement in the development of cultural, artistic, musical, recreational, social, and educational programs at the South Shore Cultural Center.

Provide a forum for discussion of concerns, interests, needs, and opportunities related to the South Shore Cultural Center and the arts.

Advise, make recommendations to, and work collaboratively with the Chicago Park District (CPD) regarding the operations, programs, preservation, and improvement of the Center.

Assist with fundraising and advocate for the preservation, maintenance, beautification, and appropriate stewardship of the Center.

Promote the growth and development of the Center as a community, regional, and citywide cultural facility.

Encourage long-range planning and responsible stewardship for the continued vitality of the Center.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-1$q$, 2, $q$II$q$, $q$Membership$q$, 1, 1, $q$Classes of Membership$q$, $q$The Council shall consist of three classes of membership: Individual, Family, and Organizational.

Membership requires submission of the Council’s membership application and payment of applicable dues within the membership year. A Family or Organization shall designate in writing one primary representative and one alternate authorized to represent that membership.

Membership shall be renewed annually.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-2$q$, 2, $q$II$q$, $q$Membership$q$, 2, 2, $q$Membership Eligibility and CPD Employees$q$, $q$Chicago Park District employees may participate as members only to the extent permitted by current Chicago Park District policies and guidelines. Where CPD policy requires an employee to be a non-voting member or restricts service as an officer, the Council shall comply with those requirements. CPD employees shall disclose their CPD employment when required.

Any question concerning whether a CPD employee may serve at a particular Park Advisory Council, including a Council serving a park in which the employee resides or works, shall be determined in accordance with current CPD policy and, when necessary, referred to the appropriate CPD office for clarification.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-3$q$, 2, $q$II$q$, $q$Membership$q$, 3, 3, $q$Member Responsibilities and Accountability$q$, $q$All members shall:

Act in the best interests of the Council and the South Shore Cultural Center.

Respect the Council’s adopted bylaws, policies, decisions, meeting procedures, and the authority of the presiding officer.

Represent the Council accurately, professionally, respectfully, and in a manner consistent with its mission when acting in an official capacity or identifying themselves as representing the Council.

Refrain from representing personal positions, unauthorized commitments, or individual disputes as official Council positions.

Protect confidential information entrusted to the Council and refrain from using Council information, resources, contacts, or property for unauthorized personal or outside purposes.

Disclose actual or potential conflicts of interest when required and refrain from using Council office or membership for improper personal benefit.

Attend meetings regularly and fulfill responsibilities accepted through election, appointment, committee assignment, or other Council action.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-4$q$, 2, $q$II$q$, $q$Membership$q$, 4, 4, $q$Membership Applications and Screening$q$, $q$Every member shall complete the required membership application. Any member whose Council duties involve contact with children, financial responsibilities, or other activities identified by CPD shall complete any required CPD volunteer application and comply with any applicable screening or background-check requirements.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-5$q$, 2, $q$II$q$, $q$Membership$q$, 5, 5, $q$Nondiscrimination$q$, $q$Membership shall be administered without unlawful discrimination and in accordance with applicable law and current Chicago Park District requirements.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-6$q$, 2, $q$II$q$, $q$Membership$q$, 6, 6, $q$Annual Dues$q$, $q$Annual dues shall be established by the Executive Board and ratified by the voting membership. The membership year shall run from January 1 through December 31. Unless changed in accordance with this provision, dues shall be $25 for Individual membership and $35 for Family and Organizational membership.

No person shall be denied an opportunity to seek membership solely because of an inability to pay dues. The Council may establish a consistent and confidential process for addressing financial hardship.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-7$q$, 2, $q$II$q$, $q$Membership$q$, 7, 7, $q$Good Standing$q$, $q$A member is in good standing when the member has satisfied applicable membership requirements, is current on dues unless an approved hardship arrangement applies, has met applicable attendance requirements, and is not under a current suspension or other disciplinary restriction.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-8$q$, 2, $q$II$q$, $q$Membership$q$, 8, 8, $q$Member and Officer Conduct; Removal$q$, $q$Officers shall be held to the highest standard of accountability because they act on behalf of the Council. Officers shall faithfully perform the duties of their offices, implement lawful Council decisions, maintain appropriate records and controls, and represent the Council professionally.

Members and officers may be subject to corrective action, suspension, removal from office, or termination of membership for conduct that is unlawful, materially inconsistent with these bylaws or CPD requirements, constitutes misuse of Council authority or resources, materially disrupts Council business, or is otherwise detrimental to the Council.

No member or officer shall be removed solely on the basis of an unsupported allegation. Except where immediate action is required by CPD policy or law, the person shall receive written notice of the concern, a reasonable opportunity to respond, and an opportunity to be heard before the final decision.

A written complaint or motion for removal shall identify the conduct at issue and shall be submitted to the Executive Board. The Executive Board shall review the matter and, when appropriate, refer it to a committee or other impartial process for fact-finding. Any officer whose conduct is the subject of the matter shall not preside over or control the review.

Following review, any proposed removal from membership or office shall be presented to the voting membership with the required notice. Removal shall require a two-thirds vote of the votes cast, unless a different requirement is imposed by applicable CPD policy, law, or a later valid bylaw provision.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$II-9$q$, 2, $q$II$q$, $q$Membership$q$, 9, 9, $q$Complaint Review and Appeal$q$, $q$The Council shall maintain a written complaint process consistent with applicable Chicago Park District guidelines. Complaints concerning a member or officer acting on behalf of the Council shall be acknowledged and addressed in writing. A complainant who remains dissatisfied after the Council’s review may request to address the general membership, subject to reasonable meeting procedures and applicable CPD requirements.

Where CPD guidelines provide for review or appeal to the CPD PAC Oversight Committee or another CPD body, the Council shall follow that process. Nothing in these bylaws shall limit or replace a right of appeal or review provided by CPD policy.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$III-1$q$, 3, $q$III$q$, $q$Meetings$q$, 1, 1, $q$Regular Meetings$q$, $q$Regular membership meetings shall be held monthly on the second Saturday of each month unless the date, time, or location is changed by the Council or circumstances require a virtual meeting. Any change shall be communicated as far in advance as reasonably practicable and, when feasible, at least forty-eight hours in advance.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$III-2$q$, 3, $q$III$q$, $q$Meetings$q$, 2, 2, $q$Annual and Election Meeting$q$, $q$The annual election meeting shall be held on the second Saturday in November. Newly elected officers shall participate in an orderly transition and shadow incumbent officers during November and December, and shall assume office in January of the following year.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$III-3$q$, 3, $q$III$q$, $q$Meetings$q$, 3, 3, $q$Meetings Open to the Public$q$, $q$Council membership meetings shall be open to the public except when an executive session is authorized under applicable rules or CPD requirements. Members in good standing who are eligible to vote shall exercise the voting rights provided by these bylaws.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$III-4$q$, 3, $q$III$q$, $q$Meetings$q$, 4, 4, $q$Notice of Meetings$q$, $q$Notice of regular membership meetings shall be posted at the South Shore Cultural Center and communicated to members using the Council’s available communication methods, including email and telephone notification systems when contact information has been provided.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$III-5$q$, 3, $q$III$q$, $q$Meetings$q$, 5, 5, $q$Special Meetings$q$, $q$A special membership meeting may be called by the President, by a majority of the Executive Board, or upon written request of at least one-fifth of the members entitled to vote. The notice shall state the time, place or electronic access information, and purpose of the meeting. No business shall be conducted at a special meeting except the business stated in the notice.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$III-6$q$, 3, $q$III$q$, $q$Meetings$q$, 6, 6, $q$Electronic and Emergency Meetings$q$, $q$When permitted by CPD requirements and these bylaws, the Council may conduct meetings by video conference, teleconference, or other electronic means that permit participating members to hear one another simultaneously. Notice shall include instructions for participation. The Council shall use reasonable procedures to verify participation, determine quorum, recognize members, receive motions, and conduct and record votes.

During a declared or significant emergency that prevents an in-person meeting, the Executive Board may take only those emergency actions reasonably necessary to preserve Council operations and comply with CPD requirements. Any such action shall be reported to the membership and entered in the minutes at the next practicable meeting.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IV-1$q$, 4, $q$IV$q$, $q$Parliamentary Authority and Voting$q$, 1, 1, $q$Parliamentary Authority$q$, $q$The rules contained in the current edition of Robert’s Rules of Order Newly Revised shall govern the Council in all cases to which they are applicable and in which they are not inconsistent with these bylaws, applicable Chicago Park District requirements, or applicable law.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IV-2$q$, 4, $q$IV$q$, $q$Parliamentary Authority and Voting$q$, 2, 2, $q$Quorum$q$, $q$A quorum for a membership meeting shall be eight (8) members who are eligible to vote. No substantive business requiring action by the membership shall be transacted in the absence of a quorum.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IV-3$q$, 4, $q$IV$q$, $q$Parliamentary Authority and Voting$q$, 3, 3, $q$Voting Eligibility$q$, $q$Voting rights for elections and bylaw amendments are limited to members in good standing who meet the eligibility requirements established by these bylaws. Only one vote shall be cast for each membership. There shall be no voting by proxy.

A member shall be considered eligible to vote if the member has attended at least four Council meetings during the twelve-month period preceding the election or bylaw vote, unless CPD requirements establish a different standard.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IV-4$q$, 4, $q$IV$q$, $q$Parliamentary Authority and Voting$q$, 4, 4, $q$Voting Method$q$, $q$Unless these bylaws or applicable rules require a ballot or another specific method, voting may be conducted by voice vote, show of hands, standing vote, roll call, ballot, or another method authorized by the chair and permitted by parliamentary procedure. The presiding officer shall announce the result of each vote.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IV-5$q$, 4, $q$IV$q$, $q$Parliamentary Authority and Voting$q$, 5, 5, $q$Majority and Special Vote Requirements$q$, $q$Unless these bylaws, CPD requirements, or applicable law require a different vote, a motion is adopted by a majority of the votes cast by members entitled to vote at a meeting at which a quorum is present. A two-thirds vote shall be required where these bylaws expressly so provide.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IV-6$q$, 4, $q$IV$q$, $q$Parliamentary Authority and Voting$q$, 6, 6, $q$Bylaw Amendments$q$, $q$An amendment to these bylaws shall be proposed by written motion and submitted to the Secretary. The proposed amendment shall be included in the notice of the meeting at which it will be considered and shall be made available to members in advance. Adoption shall require a two-thirds vote of the votes cast, with a quorum present, unless applicable CPD requirements or law impose a higher standard.

The Secretary shall maintain the adopted version and amendment history and shall make the current bylaws available to the membership, the public when required, and the Chicago Park District.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-1$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 1, 1, $q$Elected Officers$q$, $q$The elected officers of the Council shall be:

President

Vice President

Secretary

Treasurer

These officers shall constitute the Executive Board.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-2$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 2, 2, $q$Qualifications$q$, $q$A candidate for office shall satisfy membership and dues requirements, have been a Council member for at least one year, be in good standing, be eligible to vote, and satisfy all applicable CPD requirements, including any residency or other eligibility requirement. No person may serve as an officer of more than one Chicago Park District Park Advisory Council at the same time.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-3$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 3, 3, $q$General Duties and Accountability of Officers$q$, $q$Officers are entrusted with Council authority, records, resources, and responsibilities. Each officer shall:

Faithfully perform the duties of the office and comply with these bylaws, Council decisions, CPD requirements, and applicable law.

Attend Executive Board and membership meetings and communicate promptly when unable to attend.

Prepare for meetings and complete assigned follow-up actions within established deadlines.

Maintain accurate records and transfer all Council records, property, passwords, funds, and materials to the Council when leaving office.

Avoid unilateral commitments, expenditures, public statements, contracts, or representations on behalf of the Council unless authorized.

Disclose conflicts of interest and refrain from using office for personal, financial, political, or other unauthorized advantage.

Provide timely reports to the membership and support transparency, continuity, and orderly transition.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-4$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 4, 4, $q$President$q$, $q$The President shall preside at membership and Executive Board meetings, prepare or coordinate meeting agendas, ensure that adopted decisions are carried out, serve as an ex-officio member of standing committees except the Nominating Committee, and provide leadership consistent with the Council’s mission and these bylaws.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-5$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 5, 5, $q$Vice President$q$, $q$The Vice President shall perform the duties of the President in the President’s absence or inability to serve, assist with oversight of Council operations, serve as an ex-officio member of standing committees except the Nominating Committee, and perform other duties assigned by the Council.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-6$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 6, 6, $q$Secretary$q$, $q$The Secretary shall record accurate minutes of official meetings; maintain attendance records; maintain records of member good standing and voting eligibility; issue required meeting notices; maintain the official membership roster as provided by the Membership Committee; maintain the Council’s governing documents and amendment history; and provide records as authorized by the Council and CPD.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-7$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 7, 7, $q$Treasurer$q$, $q$The Treasurer shall have custody and oversight of Council funds; receive and safeguard monies; maintain complete financial records and supporting receipts; deposit funds in the Council’s authorized account; make authorized payments; provide a financial report at each regular membership meeting; provide an annual itemized financial report; and cooperate with any financial review, audit, CPD requirement, or internal control adopted by the Council.

No Council funds shall be disbursed without appropriate authorization. The Council should maintain reasonable separation of financial duties and documentation to protect both the Council and its officers.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-8$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 8, 8, $q$Executive Board Meetings and Quorum$q$, $q$The Executive Board shall meet at least four times during each fiscal year and may meet more frequently as needed. Three members of the Executive Board shall constitute a quorum. Board meetings may be conducted electronically when authorized by these bylaws.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-9$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 9, 9, $q$Vacancies and Succession$q$, $q$A vacancy in the office of President shall be filled by the Vice President for the remainder of the term unless the membership elects otherwise in accordance with these bylaws. Other vacancies shall be filled in accordance with a process approved by the Executive Board and consistent with CPD requirements, with election by the membership when required.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$V-10$q$, 5, $q$V$q$, $q$Officers and Executive Board$q$, 10, 10, $q$Removal from Office$q$, $q$An officer may be removed before the expiration of the officer’s term only through the removal procedure established in these bylaws or through another procedure required by applicable parliamentary authority, CPD requirements, or law. Where these bylaws authorize removal for cause, the officer shall receive written notice of the charges or concerns, a reasonable opportunity to respond, and the required notice of the meeting at which removal will be considered. Removal shall require a two-thirds vote of the votes cast unless a different standard is required by CPD requirements or law.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VI-1$q$, 6, $q$VI$q$, $q$Nominations and Elections$q$, 1, 1, $q$Nominating Committee$q$, $q$A Nominating Committee shall be selected at the September membership meeting. Interested voting members in good standing shall submit written interest at least one week before that meeting. The committee shall consist of no fewer than three and no more than five members.

No candidate for an office shall serve on the Nominating Committee while the committee is considering nominations for that office.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VI-2$q$, 6, $q$VI$q$, $q$Nominations and Elections$q$, 2, 2, $q$Nominations$q$, $q$The Nominating Committee shall present its report at the November election meeting. Additional nominations may be made from the floor when permitted by parliamentary procedure and the Council’s adopted election procedures.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VI-3$q$, 6, $q$VI$q$, $q$Nominations and Elections$q$, 3, 3, $q$Elections$q$, $q$Officers shall be elected at the November election meeting by the voting membership. Elections shall be conducted in a fair and orderly manner consistent with parliamentary procedure and any applicable CPD requirements. When more than one candidate is nominated for an office, the election shall be conducted by ballot unless the assembly lawfully adopts another permissible method.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VI-4$q$, 6, $q$VI$q$, $q$Nominations and Elections$q$, 4, 4, $q$Transition$q$, $q$Incoming officers shall shadow incumbent officers during November and December. Incumbent officers shall provide a timely transition of records, financial information, passwords, keys, equipment, correspondence, and other Council property so that the incoming officers can assume their responsibilities in January.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VII-1$q$, 7, $q$VII$q$, $q$Committees and Appointed Positions$q$, 1, 1, $q$Standing Committees$q$, $q$Standing committees shall be composed of Council members and, when appropriate and permitted, other volunteers. Committee Chairs shall be appointed by the Executive Board. The President and Vice President shall be ex-officious members of standing committees and task forces except the Nominating Committee. Officers shall not serve as standing committee Chairs unless the Council expressly authorizes an exception consistent with CPD requirements.

Standing committees shall meet at least every two months unless their work is completed or the Executive Board determines that a different schedule is appropriate. Chairs shall provide notice of committee meetings to the membership, submit reports at regular membership meetings, and provide written reports or records to the Secretary.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VII-2$q$, 7, $q$VII$q$, $q$Committees and Appointed Positions$q$, 2, 2, $q$Committee Accountability$q$, $q$Each committee shall operate within the purpose assigned to it and shall not independently bind the Council, commit Council funds, enter agreements, make official public statements, or represent an action as approved by the Council unless authorized.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VII-3$q$, 7, $q$VII$q$, $q$Committees and Appointed Positions$q$, 3, 3, $q$Standing Committees$q$, $q$Performing Arts Committee: Develops and promotes art, music, and cultural programs and events for the community.

Building and Grounds Committee: Reviews conditions of park facilities, equipment, and surrounding parkland and recommends repair, landscaping, renovation, replacement, maintenance, or beautification.

Program Committee: Assesses programming needs, develops recommendations to CPD, and develops and organizes cultural programs and events approved by the Council.

Fundraising Committee: Develops and supports lawful fundraising, sponsorship, grant, and other resource-development activities to support Council-approved programming and community needs.

Membership and Community Outreach Committee: Recruits and engages members, supports outreach at Park events, maintains an up-to-date membership roll, and provides membership information to the Secretary.

Marketing and Technical Committee: Maintains Council-approved social media and communications content and supports virtual meetings and related technology.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VII-4$q$, 7, $q$VII$q$, $q$Committees and Appointed Positions$q$, 4, 4, $q$Appointed Position – Sergeant-at-Arms$q$, $q$The Sergeant-at-Arms shall be appointed by the presiding officer or Executive Board as authorized and shall assist in maintaining order and decorum at meetings. The Sergeant-at-Arms shall follow the direction of the presiding officer and shall not exercise independent disciplinary authority beyond that assigned by the Council or its presiding officer.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VIII-1$q$, 8, $q$VIII$q$, $q$Ethics, Conflicts, and Use of Council Authority$q$, 1, 1, $q$Ethical Conduct$q$, $q$All officers and members shall conduct Council business honestly, respectfully, transparently, and in good faith.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VIII-2$q$, 8, $q$VIII$q$, $q$Ethics, Conflicts, and Use of Council Authority$q$, 2, 2, $q$Conflicts of Interest$q$, $q$An officer or member who has a direct personal or financial interest in a matter before the Council shall disclose the conflict. The Council may take appropriate action under applicable parliamentary rules, CPD requirements, or an adopted conflict-of-interest policy.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VIII-3$q$, 8, $q$VIII$q$, $q$Ethics, Conflicts, and Use of Council Authority$q$, 3, 3, $q$Council Representation$q$, $q$Only persons authorized by the Council may make official statements, commitments, or representations on behalf of the Council. Members speaking in an individual capacity shall make clear that they are not speaking for the Council when a reasonable person could otherwise understand the communication to be an official Council position.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$VIII-4$q$, 8, $q$VIII$q$, $q$Ethics, Conflicts, and Use of Council Authority$q$, 4, 4, $q$Council Property and Resources$q$, $q$Council funds, records, equipment, communication accounts, logos, passwords, contact lists, and other resources shall be used only for authorized Council purposes and shall be returned or transferred promptly upon request or upon the end of service.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IX-1$q$, 9, $q$IX$q$, $q$Records, Transparency, and Reporting$q$, 1, 1, $q$Minutes and Records$q$, $q$The Secretary shall maintain the official minutes and governing records of the Council. Minutes shall reflect actions taken, including motions adopted or rejected, and shall be maintained in an orderly manner.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IX-2$q$, 9, $q$IX$q$, $q$Records, Transparency, and Reporting$q$, 2, 2, $q$Financial Reporting$q$, $q$Financial reports shall be presented to the membership regularly as required by these bylaws. Supporting records shall be maintained in accordance with Council and CPD requirements.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$IX-3$q$, 9, $q$IX$q$, $q$Records, Transparency, and Reporting$q$, 3, 3, $q$Annual Accountability$q$, $q$At least annually, the Executive Board shall provide the membership with a summary of Council activities, committee work, membership status, finances, major recommendations, and priorities for the coming year.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$X-1$q$, 10, $q$X$q$, $q$Amendments$q$, 1, 1, $q$Amendment Procedure$q$, $q$These bylaws may be amended, revised, or repealed only by action of the voting membership in accordance with this Article. Proposed amendments shall be submitted in writing to the Secretary and shall identify the Article and Section affected.

The proposed amendment shall be provided to members with the notice of the meeting at which it will be considered, and no amendment shall be adopted without the required previous notice.

A two-thirds vote of the votes cast, with a quorum present, shall be required for adoption unless applicable CPD requirements or law require a higher standard.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$X-2$q$, 10, $q$X$q$, $q$Amendments$q$, 2, 2, $q$Records and Distribution$q$, $q$The Secretary shall update the official bylaws, record the date and substance of each adopted amendment, and make the current version available to the membership, the public when required, and the Chicago Park District.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$XI-1$q$, 11, $q$XI$q$, $q$Effective Date and Governing Requirements$q$, 1, 1, $q$Effective Date$q$, $q$These revised bylaws shall become effective upon lawful adoption by the Council and any required review, approval, or acknowledgment by the Chicago Park District.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$XI-2$q$, 11, $q$XI$q$, $q$Effective Date and Governing Requirements$q$, 2, 2, $q$Superseding Provisions$q$, $q$Upon adoption, these bylaws supersede prior Council bylaws to the extent of any conflict.$q$);
insert into sscc_bylaws_sections (key, article_order, article_num, article_title, section_order, section_num, title, body) values ($q$XI-3$q$, 11, $q$XI$q$, $q$Effective Date and Governing Requirements$q$, 3, 3, $q$Compliance with CPD Requirements$q$, $q$Nothing in these bylaws shall be interpreted to authorize conduct prohibited by Chicago Park District policy, applicable law, or other controlling requirements. Where a conflict exists, the Council shall follow the controlling requirement and seek clarification from CPD when appropriate.$q$);
insert into sscc_bylaws_versions (num, label, summary, created_by_label, snapshot) values (1, 'v1.0', 'Proposed revision as drafted by a committee member (Clean Bylaws Revision), before any committee changes. Not adopted: the 2022 bylaws remain in force.', 'Bylaws subcommittee', sscc_bylaws_snapshot());
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$VII-1$q$, $q$VII$q$, $q$Typo: "ex-officious" should be "ex-officio"$q$, $q$Section 1 says the President and Vice President "shall be ex-officious members of standing committees." The term used everywhere else (V.4, V.5) is "ex-officio."$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$VII-3$q$, $q$VII$q$, $q$Two sections in Article VII are both titled "Standing Committees"$q$, $q$Section 1 and Section 3 share the same title. Section 3 lists the committees; a distinct title (for example "List of Standing Committees") would make cross-references unambiguous.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$IV-6$q$, $q$IV$q$, $q$Amendment procedure appears twice (IV.6 and Article X)$q$, $q$IV.6 and X.1 both set the amendment procedure, with slightly different wording (only X.1 requires identifying the Article and Section affected). Consider keeping the procedure in one place and cross-referencing it from the other, so the two cannot drift apart.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$X-1$q$, $q$X$q$, $q$"Required previous notice" for amendments is never defined$q$, $q$X.1 says no amendment shall be adopted "without the required previous notice," and IV.6 says the amendment is included in the meeting notice, but neither says how far in advance (for example, at a prior regular meeting or a set number of days before the vote).$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$V-10$q$, $q$V$q$, $q$Removal is covered in both II.8 and V.10$q$, $q$II.8 sets a detailed removal process for members and officers; V.10 repeats officer removal with different wording ("or through another procedure required by applicable parliamentary authority"). Check that the two agree, or have V.10 point to II.8.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$V-8$q$, $q$V$q$, $q$"Fiscal year" is used but never defined$q$, $q$V.8 requires Executive Board meetings "at least four times during each fiscal year." II.6 defines the membership year (January 1 to December 31) but the fiscal year is not defined anywhere.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$II-7$q$, $q$II$q$, $q$Good standing refers to "applicable attendance requirements" that are not stated$q$, $q$II.7 includes meeting "applicable attendance requirements" in good standing. The only attendance rule in the bylaws is the voting-eligibility rule in IV.3 (four meetings in twelve months). Say whether that is the requirement, or define a separate one.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$IV-2$q$, $q$IV$q$, $q$Quorum: does it count people or memberships?$q$, $q$IV.2 sets quorum at eight members eligible to vote, while IV.3 allows only one vote per membership (Family and Organizational memberships included). Clarify whether two people from one Family membership count once or twice toward quorum.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$V-2$q$, $q$V$q$, $q$"A Council member for at least one year": continuous, or total?$q$, $q$V.2 requires officer candidates to have been members for at least one year. Clarify whether that means one continuous year immediately before the election, and how lapsed dues affect it.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$V-9$q$, $q$V$q$, $q$Vacancies other than President: the process is left to the Executive Board$q$, $q$V.9 says other vacancies are filled "in accordance with a process approved by the Executive Board." Consider stating the process in the bylaws (who nominates, whether the membership votes, and for what term).$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$VII-4$q$, $q$VII$q$, $q$Who appoints the Sergeant-at-Arms, and for how long?$q$, $q$VII.4 says the Sergeant-at-Arms is appointed "by the presiding officer or Executive Board as authorized." Name one appointing authority and a term.$q$, 'Starter review');
insert into sscc_bylaws_proposals (kind, section_key, article_num, summary, rationale, author_label) values ('issue', $q$II-9$q$, $q$II$q$, $q$Confirm CPD body names and current PAC guidelines$q$, $q$II.9 refers to review or appeal by the "CPD PAC Oversight Committee." CPD's current PAC Guidelines do not mention a PAC Oversight Committee: complaints about a PAC or its members go to the Park Supervisor or Area Manager, with a written appeal filed there. Confirm the correct body with CPD and update II.9 (and any other references to CPD bodies) before adoption.$q$, 'Starter review');
end;
$seed$;
