"""Re-syncs plates_for_purpose_restaurants from the Caribbean Restaurant CRM
spreadsheet. Safe to re-run any time the spreadsheet is updated -- existing
rows are upserted (matched by slug), not skipped, so corrections/additions
in the sheet actually take effect.

Deliberately does NOT touch contact_status, logo_path, or
count_toward_public_tally on existing rows -- those are live-tracked in
Supabase (set by staff as donations get confirmed, logos get uploaded, etc.),
not sourced from the spreadsheet, and a blind overwrite would silently
revert real progress back to the sheet's stale snapshot. New rows still get
sensible defaults for those three columns.

Usage:
    python sync-plates-for-purpose-restaurants.py [path-to-crm.xlsx]
    (defaults to the path below if omitted)

Writes the generated SQL to sync_output.sql next to this script -- inspect
it, then apply with:
    supabase db query --linked -f supabase/sync_output.sql
This script does NOT apply the SQL itself, so a bad spreadsheet edit can't
silently corrupt the live table.
"""
import sys
import re
import os
import openpyxl

DEFAULT_CRM_PATH = r"C:\Users\mkepr\Documents\Fest\Sponsor\SelassieFest_CaribbeanRestarant_CRM.xlsx"
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "sync_output.sql")


def slugify(name):
    s = name.lower().replace('&', 'and')
    s = re.sub(r"[().,']", '', s)
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return re.sub(r'-+', '-', s).strip('-')


def sql_str(v):
    if v is None or v == '' or v == 'Unknown':
        return 'null'
    return "'" + str(v).replace("'", "''") + "'"


def main():
    crm_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CRM_PATH
    wb = openpyxl.load_workbook(crm_path, data_only=True)
    ws = wb.worksheets[0]
    rows = list(ws.iter_rows(min_row=1, values_only=True))
    headers = rows[0]
    records = [dict(zip(headers, r)) for r in rows[1:] if r[0]]

    seen = {}
    def unique_slug(name):
        base = slugify(name)
        if base not in seen:
            seen[base] = 1
            return base
        seen[base] += 1
        return f"{base}-{seen[base]}"

    value_rows = []
    for r in records:
        slug = unique_slug(r['Business Name'])
        vals = [
            sql_str(slug),
            sql_str(r['Business Name']),
            sql_str(r.get('Address')),
            sql_str(r.get('Phone')),
            sql_str(r.get('Email')),
            sql_str(r.get('Website')),
            sql_str(r.get('Owner/Decision Maker')),
            sql_str(r.get('Instagram')),
            sql_str(r.get('Facebook')),
            sql_str(r.get('Donation Ask')),
            sql_str(r.get('Target Ask Value')),
            sql_str(r.get('Suggested Donation')),
            sql_str(r.get('Partnership Potential')),
            sql_str(r.get('Notes')),
        ]
        value_rows.append('  (' + ', '.join(vals) + ')')

    cols = "(slug, business_name, address, phone, email, website, owner_name, instagram, facebook, donation_ask, target_ask_value, suggested_donation, partnership_potential, notes)"
    sql = f"""-- Auto-generated by sync-plates-for-purpose-restaurants.py from:
-- {crm_path}
-- Review before applying. Does NOT touch contact_status, logo_path, or
-- count_toward_public_tally on existing rows.
insert into plates_for_purpose_restaurants {cols}
values
""" + ',\n'.join(value_rows) + f"""
on conflict (slug) do update set
  business_name = excluded.business_name,
  address = excluded.address,
  phone = excluded.phone,
  email = excluded.email,
  website = excluded.website,
  owner_name = excluded.owner_name,
  instagram = excluded.instagram,
  facebook = excluded.facebook,
  donation_ask = excluded.donation_ask,
  target_ask_value = excluded.target_ask_value,
  suggested_donation = excluded.suggested_donation,
  partnership_potential = excluded.partnership_potential,
  notes = excluded.notes;
"""

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(sql)

    print(f"{len(records)} rows read from {crm_path}")
    print(f"SQL written to {OUTPUT_PATH} -- review, then apply with:")
    print(f"  supabase db query --linked -f supabase/sync_output.sql")


if __name__ == '__main__':
    main()
